#!/bin/bash

# Script: Ops 201 Class 01 Ops Challenge Solution
# Author: 
# Date of latest revision: 
# Purpose: Print a string to the terminal
 # # We can do math inside a variable by coding like the example below
total=$((Number1 * Number2))
#we can use a variable and user created text when echo stuff out also
# echo $total
# echo "your total is "  $total

# echo $Number1
# echo $Number2
# echo "Bash is a new learning curve"

# Bash Butler
# bestdayever.sh

Name =$1

echo "Good Morning $name"
sleep 1
echo "You are the best $name!"
sleep 1
./


